# Generated by Django 6.0.6 on 2026-06-05 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id_vacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('desc_tipo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVacunacion',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('campanas', models.ManyToManyField(related_name='puntos_vacunacion', to='mi_app.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('punto_vacunacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='mi_app.puntovacunacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.campana')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mi_app.persona')),
                ('punto_vacunacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.puntovacunacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id_vacunacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mi_app.cita')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='mi_app.persona')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_app.personal')),
                ('tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_app.tipovacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.IntegerField(default=0)),
                ('stock_reservado', models.IntegerField(default=0)),
                ('punto_vacunacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='mi_app.puntovacunacion')),
                ('tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.tipovacuna')),
            ],
            options={
                'unique_together': {('punto_vacunacion', 'tipo_vacuna')},
            },
        ),
    ]
