# Generated by Django 6.0.6 on 2026-06-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='tipo_vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='mi_app.tipovacuna'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Agendada', max_length=50),
        ),
    ]
