# Generated by Django 6.0.6 on 2026-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_campana_tipo_vacuna_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='tipo_vacuna',
        ),
        migrations.AddField(
            model_name='campana',
            name='tipos_vacuna',
            field=models.ManyToManyField(blank=True, related_name='campanas', to='mi_app.tipovacuna'),
        ),
    ]
