# Generated by Django 6.0.6 on 2026-06-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_remove_campana_tipo_vacuna_campana_tipos_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.tipovacuna'),
        ),
    ]
